[package]
name = "clique"
version = "0.1.0"
authors = ["aaronmck <aaronatwpi@gmail.com>"]
edition = "2021"

[dependencies]
bio = "*"
clap = { version = "3.1.6", features = ["derive"] }
lazy_static = "1.4.0"
csv = "1.1"
rand = "*"
needletail = "0.4"
actix = "0.12"
actix-rt = "1.1"
tokio = { version = "1.17.0", features = ["full"] }

[profile.release]

[build]
rustflags = "-C target-cpu=native"
